#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import os
import re

def usage():
    print('show git submodule modification')
    print('usage:')
    print(sys.argv[0] + ' <commit1> <commit2> <index of submoudle>   # show diff between the two commits')
    print(sys.argv[0] + ' <commit> <index of submoudle>            # show diff between commit and HEAD')


if __name__ == '__main__':

    if len(sys.argv) < 3:
        usage()
        sys.exit(0)

    commit2 = ''
    if len(sys.argv) == 3:
        commit1 = sys.argv[1]
        index = int(sys.argv[2])
    if len(sys.argv) == 4:
        commit1 = sys.argv[1]
        commit2 = sys.argv[2]
        index = int(sys.argv[3])

    if commit2:
        cmd = 'git diff %s %s > /tmp/git_diff_sub' % (commit1, commit2)
    else:
        cmd = 'git diff %s > /tmp/git_diff_sub' % (commit1)
    r = os.system(cmd)

    p = r'.*?a/(.*)\sb/(.*)'
    subs = []
    item = ''     # submodule dir
    commits = []  # submodule commit
    if r == 0:
        with open('/tmp/git_diff_sub') as f:
            while True:
                line = f.readline()
                if not line:
                    break

                line = line.strip()

                if line.startswith('diff --git'):
                    m = re.match(p, line)
                    if m:
                        item = m.group(1)
                        commits = []

                if line.startswith('-Subproject commit'):
                    if line.find('-dirty') >= 0:
                        line = line[:line.find('-dirty')]
                    commits.append(line.split()[2])
                if line.startswith('+Subproject commit'):
                    if line.find('-dirty') >= 0:
                        line = line[:line.find('-dirty')]
                    commits.append(line.split()[2])
                    subs.append((item, commits))
        print('%d submodules modified' % (len(subs)))

        currdir = os.getcwd()

        index -= 1
        if commit2:
            print('Showing %dst submodule [%s] difference of commit %s and %s' % (index + 1, subs[index][0], commit1, commit2))
        else:
            print('Showing %dst submodule [%s] difference of commit %s and HEAD' % (index + 1, subs[index][0], commit1))

        # find git root dir
        root = currdir
        while True:
            d = os.path.join(root, ".git")
            if os.path.exists(d):
                break
            else:
                root = os.path.join(root, '../')

        os.chdir(os.path.join(root, subs[index][0]))

        cmd = 'git diff --stat %s %s' % (subs[index][1][0], subs[index][1][1])
        os.system(cmd)

        print('Press ENTER to continue...')
        raw_input()

        cmd = 'git diff %s %s' % (subs[index][1][0], subs[index][1][1])
        os.system(cmd)

        os.chdir(currdir)


